### ISSUE TITLE
Error in FireFox

### ISSUE THREAD

**Issue by amousavii** [BernhardtD/vue-sorted-table#19]
I have used this package in my project and it works great in Chrome but in FireFox i have this following Error in Console:
`TypeError: this.values.slice().sort is not a function`
Any advice ?

**Comment by BernhardtD** [comment]
It's not clear, where the issue occurs. Please prepare an example on CodeSandbox to get more information.

**Comment by BernhardtD** [comment]
No issue activity. Closed.
