### ISSUE TITLE
Date sorting

### ISSUE THREAD

**Issue by projct1** [BernhardtD/vue-sorted-table#25]
Hi!
This plugin cant sort dates?
https://skr.sh/s7bnHC86cT0
All dates only in bottom all time https://skr.sh/s7bb7nBuEny

**Comment by BernhardtD** [comment]
Duplicate of #17 . Closed.

**Comment by projct1** [comment]
Thanks. But i moved to https://xaksis.github.io/vue-good-table/ and happy) Totally no pain now)
