### ISSUE TITLE
sort case insensitive

### ISSUE THREAD

**Issue by christophstockinger** [BernhardtD/vue-sorted-table#3]
Hi @BernhardtD,

great work! 

I need your help. I'd like to sort through case insensitive. Is it possible to allow this as an option or do you have an alternative solution?

Thanks for an answer!

**Comment by BernhardtD** [comment]
Hi @christophstockinger,

you should provide a custom sorting function. The `SortedTable` component provides the property `onSort`, which should be a callback to sort the given value array. The first argument of the custom sorting function is the selected property (e.g. 'id') and the second argument is the direction ('asc' or 'desc').

**Comment by christophstockinger** [comment]
@BernhardtD  Thanks for your answer. It works.
